// <auto-generated />
using System;
using Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Booking.Models.FavoriteHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteHotels");
                });

            modelBuilder.Entity("Booking.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableRoomsCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AvailableRoomsCount = 4,
                            City = "Київ",
                            ImagePath = "/images/1.jpg",
                            Name = "Premier Palace Hotel",
                            PricePerNight = 5000m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AvailableRoomsCount = 2,
                            City = "Київ",
                            ImagePath = "/images/2.jpg",
                            Name = "Hilton Kyiv",
                            PricePerNight = 7500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AvailableRoomsCount = 3,
                            City = "Одеса",
                            ImagePath = "/images/3.jpg",
                            Name = "M1 Club Hotel",
                            PricePerNight = 4500m,
                            Rating = 9.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AvailableRoomsCount = 5,
                            City = "Одеса",
                            ImagePath = "/images/4.jpg",
                            Name = "Bristol Hotel",
                            PricePerNight = 3200m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AvailableRoomsCount = 6,
                            City = "Львів",
                            ImagePath = "/images/5.jpg",
                            Name = "Bankhotel",
                            PricePerNight = 4100m,
                            Rating = 9.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AvailableRoomsCount = 3,
                            City = "Львів",
                            ImagePath = "/images/6.jpg",
                            Name = "Grand Hotel Lviv",
                            PricePerNight = 3800m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AvailableRoomsCount = 7,
                            City = "Харків",
                            ImagePath = "/images/7.jpg",
                            Name = "Kharkiv Palace",
                            PricePerNight = 3500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AvailableRoomsCount = 4,
                            City = "Харків",
                            ImagePath = "/images/8.jpg",
                            Name = "Nemo Hotel Kharkiv",
                            PricePerNight = 4200m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AvailableRoomsCount = 10,
                            City = "Дніпро",
                            ImagePath = "/images/9.jpg",
                            Name = "Menorah Hotel",
                            PricePerNight = 2900m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AvailableRoomsCount = 2,
                            City = "Дніпро",
                            ImagePath = "/images/10.jpg",
                            Name = "Bartolomeo Resort",
                            PricePerNight = 4800m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AvailableRoomsCount = 5,
                            City = "Вінниця",
                            ImagePath = "/images/11.jpg",
                            Name = "Hotel France",
                            PricePerNight = 2500m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            AvailableRoomsCount = 3,
                            City = "Вінниця",
                            ImagePath = "/images/12.jpg",
                            Name = "Feride Hotel",
                            PricePerNight = 2800m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            AvailableRoomsCount = 2,
                            City = "Луцьк",
                            ImagePath = "/images/13.jpg",
                            Name = "Noble Boutique Hotel",
                            PricePerNight = 2300m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            AvailableRoomsCount = 6,
                            City = "Луцьк",
                            ImagePath = "/images/14.jpg",
                            Name = "Zalesie Hotel",
                            PricePerNight = 1800m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            AvailableRoomsCount = 5,
                            City = "Донецьк",
                            ImagePath = "/images/15.jpg",
                            Name = "Donbass Palace",
                            PricePerNight = 4000m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            AvailableRoomsCount = 8,
                            City = "Донецьк",
                            ImagePath = "/images/16.jpg",
                            Name = "Victoria Hotel",
                            PricePerNight = 3500m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            AvailableRoomsCount = 12,
                            City = "Житомир",
                            ImagePath = "/images/17.jpg",
                            Name = "Reikartz Zhytomyr",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            AvailableRoomsCount = 4,
                            City = "Житомир",
                            ImagePath = "/images/18.jpg",
                            Name = "Chalet Hotel",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            AvailableRoomsCount = 5,
                            City = "Ужгород",
                            ImagePath = "/images/19.jpg",
                            Name = "Hotel Duet Plus",
                            PricePerNight = 2600m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            AvailableRoomsCount = 7,
                            City = "Ужгород",
                            ImagePath = "/images/20.jpg",
                            Name = "Praha Hotel",
                            PricePerNight = 2200m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            AvailableRoomsCount = 8,
                            City = "Запоріжжя",
                            ImagePath = "/images/21.jpg",
                            Name = "Khortitsa Palace",
                            PricePerNight = 3100m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            AvailableRoomsCount = 15,
                            City = "Запоріжжя",
                            ImagePath = "/images/22.jpg",
                            Name = "Intourist Hotel",
                            PricePerNight = 1900m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            AvailableRoomsCount = 6,
                            City = "Івано-Франківськ",
                            ImagePath = "/images/23.jpg",
                            Name = "Nadiya Hotel",
                            PricePerNight = 2400m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            AvailableRoomsCount = 4,
                            City = "Івано-Франківськ",
                            ImagePath = "/images/24.jpg",
                            Name = "Stanislaviv",
                            PricePerNight = 2000m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            AvailableRoomsCount = 9,
                            City = "Кропивницький",
                            ImagePath = "/images/25.jpg",
                            Name = "Reikartz Kropyvnytskyi",
                            PricePerNight = 2200m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            AvailableRoomsCount = 11,
                            City = "Кропивницький",
                            ImagePath = "/images/26.jpg",
                            Name = "Hotel Zirka",
                            PricePerNight = 1600m,
                            Rating = 8.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            AvailableRoomsCount = 5,
                            City = "Луганськ",
                            ImagePath = "/images/27.jpg",
                            Name = "Hotel Initial",
                            PricePerNight = 1800m,
                            Rating = 8.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            AvailableRoomsCount = 8,
                            City = "Луганськ",
                            ImagePath = "/images/28.jpg",
                            Name = "Druzhba Hotel",
                            PricePerNight = 1500m,
                            Rating = 8.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            AvailableRoomsCount = 7,
                            City = "Миколаїв",
                            ImagePath = "/images/29.jpg",
                            Name = "Reikartz River",
                            PricePerNight = 2500m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            AvailableRoomsCount = 4,
                            City = "Миколаїв",
                            ImagePath = "/images/30.jpg",
                            Name = "Palace Ukraine",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            AvailableRoomsCount = 3,
                            City = "Полтава",
                            ImagePath = "/images/31.jpg",
                            Name = "Premier Hotel Palazzo",
                            PricePerNight = 2700m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            AvailableRoomsCount = 6,
                            City = "Полтава",
                            ImagePath = "/images/32.jpg",
                            Name = "Reikartz Gallery",
                            PricePerNight = 2300m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            AvailableRoomsCount = 2,
                            City = "Рівне",
                            ImagePath = "/images/33.jpg",
                            Name = "Boutique Hotel",
                            PricePerNight = 2600m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            AvailableRoomsCount = 8,
                            City = "Рівне",
                            ImagePath = "/images/34.jpg",
                            Name = "Optima Rivne",
                            PricePerNight = 1900m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            AvailableRoomsCount = 5,
                            City = "Суми",
                            ImagePath = "/images/35.jpg",
                            Name = "Reikartz Sumy",
                            PricePerNight = 2000m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            AvailableRoomsCount = 3,
                            City = "Суми",
                            ImagePath = "/images/36.jpg",
                            Name = "Shafran Hotel",
                            PricePerNight = 2200m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            AvailableRoomsCount = 6,
                            City = "Тернопіль",
                            ImagePath = "/images/37.jpg",
                            Name = "Avalon Palace",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            AvailableRoomsCount = 4,
                            City = "Тернопіль",
                            ImagePath = "/images/38.jpg",
                            Name = "Garden Hall",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            AvailableRoomsCount = 10,
                            City = "Херсон",
                            ImagePath = "/images/39.jpg",
                            Name = "Optima Kherson",
                            PricePerNight = 1800m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            AvailableRoomsCount = 3,
                            City = "Херсон",
                            ImagePath = "/images/40.jpg",
                            Name = "Play Hotel by Ribas",
                            PricePerNight = 2300m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            AvailableRoomsCount = 4,
                            City = "Хмельницький",
                            ImagePath = "/images/41.jpg",
                            Name = "Arena Hotel",
                            PricePerNight = 2500m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            AvailableRoomsCount = 2,
                            City = "Хмельницький",
                            ImagePath = "/images/42.jpg",
                            Name = "Sobkoff Hotel",
                            PricePerNight = 2800m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            AvailableRoomsCount = 6,
                            City = "Черкаси",
                            ImagePath = "/images/43.jpg",
                            Name = "Apelsin Hotel",
                            PricePerNight = 2200m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            AvailableRoomsCount = 8,
                            City = "Черкаси",
                            ImagePath = "/images/44.jpg",
                            Name = "Optima Cherkasy",
                            PricePerNight = 1900m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            AvailableRoomsCount = 5,
                            City = "Чернівці",
                            ImagePath = "/images/45.jpg",
                            Name = "Bukovyna Hotel",
                            PricePerNight = 2700m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            AvailableRoomsCount = 2,
                            City = "Чернівці",
                            ImagePath = "/images/46.jpg",
                            Name = "AllureInn",
                            PricePerNight = 3000m,
                            Rating = 9.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            AvailableRoomsCount = 7,
                            City = "Чернігів",
                            ImagePath = "/images/47.jpg",
                            Name = "Riverside Resort",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            AvailableRoomsCount = 5,
                            City = "Чернігів",
                            ImagePath = "/images/48.jpg",
                            Name = "Reikartz Chernihiv",
                            PricePerNight = 2100m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            AvailableRoomsCount = 4,
                            City = "Сімферополь",
                            ImagePath = "/images/49.jpg",
                            Name = "Ukraina Hotel",
                            PricePerNight = 3500m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            AvailableRoomsCount = 2,
                            City = "Ялта",
                            ImagePath = "/images/50.jpg",
                            Name = "Yalta Intourist",
                            PricePerNight = 5500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            AvailableRoomsCount = 8,
                            City = "Буковель",
                            ImagePath = "/images/51.jpg",
                            Name = "Radisson Blu Resort",
                            PricePerNight = 6200m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            AvailableRoomsCount = 5,
                            City = "Буковель",
                            ImagePath = "/images/52.jpg",
                            Name = "F&B Spa Resort",
                            PricePerNight = 5100m,
                            Rating = 9.0
                        });
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsAvailable = true,
                            PricePerNight = 5000m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsAvailable = true,
                            PricePerNight = 7500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IsAvailable = true,
                            PricePerNight = 4500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000004"),
                            IsAvailable = true,
                            PricePerNight = 3200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IsAvailable = true,
                            PricePerNight = 4100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000006"),
                            IsAvailable = true,
                            PricePerNight = 3800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000007"),
                            IsAvailable = true,
                            PricePerNight = 3500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000008"),
                            IsAvailable = true,
                            PricePerNight = 4200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IsAvailable = true,
                            PricePerNight = 2900m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000010"),
                            IsAvailable = true,
                            PricePerNight = 4800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000011"),
                            IsAvailable = true,
                            PricePerNight = 2500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000012"),
                            IsAvailable = true,
                            PricePerNight = 2800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000013"),
                            IsAvailable = true,
                            PricePerNight = 2300m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000014"),
                            IsAvailable = true,
                            PricePerNight = 1800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000015"),
                            IsAvailable = true,
                            PricePerNight = 4000m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000016"),
                            IsAvailable = true,
                            PricePerNight = 3500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000017"),
                            IsAvailable = true,
                            PricePerNight = 2100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000018"),
                            IsAvailable = true,
                            PricePerNight = 2400m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000019"),
                            IsAvailable = true,
                            PricePerNight = 2600m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000020"),
                            IsAvailable = true,
                            PricePerNight = 2200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000021"),
                            IsAvailable = true,
                            PricePerNight = 3100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000022"),
                            IsAvailable = true,
                            PricePerNight = 1900m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000023"),
                            IsAvailable = true,
                            PricePerNight = 2400m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000024"),
                            IsAvailable = true,
                            PricePerNight = 2000m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000025"),
                            IsAvailable = true,
                            PricePerNight = 2200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000026"),
                            IsAvailable = true,
                            PricePerNight = 1600m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000027"),
                            IsAvailable = true,
                            PricePerNight = 1800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000028"),
                            IsAvailable = true,
                            PricePerNight = 1500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000029"),
                            IsAvailable = true,
                            PricePerNight = 2500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000030"),
                            IsAvailable = true,
                            PricePerNight = 2100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000031"),
                            IsAvailable = true,
                            PricePerNight = 2700m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000032"),
                            IsAvailable = true,
                            PricePerNight = 2300m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000033"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000033"),
                            IsAvailable = true,
                            PricePerNight = 2600m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000034"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000034"),
                            IsAvailable = true,
                            PricePerNight = 1900m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000035"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000035"),
                            IsAvailable = true,
                            PricePerNight = 2000m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000036"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000036"),
                            IsAvailable = true,
                            PricePerNight = 2200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000037"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000037"),
                            IsAvailable = true,
                            PricePerNight = 2400m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000038"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000038"),
                            IsAvailable = true,
                            PricePerNight = 2100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000039"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000039"),
                            IsAvailable = true,
                            PricePerNight = 1800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000040"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000040"),
                            IsAvailable = true,
                            PricePerNight = 2300m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000041"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000041"),
                            IsAvailable = true,
                            PricePerNight = 2500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000042"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000042"),
                            IsAvailable = true,
                            PricePerNight = 2800m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000043"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000043"),
                            IsAvailable = true,
                            PricePerNight = 2200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000044"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000044"),
                            IsAvailable = true,
                            PricePerNight = 1900m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000045"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000045"),
                            IsAvailable = true,
                            PricePerNight = 2700m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000046"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000046"),
                            IsAvailable = true,
                            PricePerNight = 3000m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000047"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000047"),
                            IsAvailable = true,
                            PricePerNight = 2400m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000048"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000048"),
                            IsAvailable = true,
                            PricePerNight = 2100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000049"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000049"),
                            IsAvailable = true,
                            PricePerNight = 3500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000050"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000050"),
                            IsAvailable = true,
                            PricePerNight = 5500m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000051"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000051"),
                            IsAvailable = true,
                            PricePerNight = 6200m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000052"),
                            Capacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000052"),
                            IsAvailable = true,
                            PricePerNight = 5100m,
                            RoomNumber = "101",
                            RoomType = "Standard"
                        });
                });

            modelBuilder.Entity("Booking.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Booking.Models.Booking", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.FavoriteHotel", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Booking.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Booking.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
