// <auto-generated />
using System;
using Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Booking.Models.FavoriteHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteHotels");
                });

            modelBuilder.Entity("Booking.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableRoomsCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AvailableRoomsCount = 4,
                            City = "Київ",
                            ImagePath = "https://images.unsplash.com/photo-1551882547-ff40c0d1398c",
                            Name = "Premier Palace Hotel",
                            PricePerNight = 5000m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AvailableRoomsCount = 2,
                            City = "Київ",
                            ImagePath = "https://images.unsplash.com/photo-1542314831-c6a4d27ce006",
                            Name = "Hilton Kyiv",
                            PricePerNight = 7500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AvailableRoomsCount = 3,
                            City = "Одеса",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Name = "M1 Club Hotel",
                            PricePerNight = 4500m,
                            Rating = 9.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AvailableRoomsCount = 5,
                            City = "Одеса",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
                            Name = "Bristol Hotel",
                            PricePerNight = 3200m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AvailableRoomsCount = 6,
                            City = "Львів",
                            ImagePath = "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
                            Name = "Bankhotel",
                            PricePerNight = 4100m,
                            Rating = 9.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AvailableRoomsCount = 3,
                            City = "Львів",
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            Name = "Grand Hotel Lviv",
                            PricePerNight = 3800m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AvailableRoomsCount = 7,
                            City = "Харків",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Kharkiv Palace",
                            PricePerNight = 3500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AvailableRoomsCount = 4,
                            City = "Харків",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "Nemo Hotel Kharkiv",
                            PricePerNight = 4200m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AvailableRoomsCount = 10,
                            City = "Дніпро",
                            ImagePath = "https://images.unsplash.com/photo-1618773928121-c32242fa4703",
                            Name = "Menorah Hotel",
                            PricePerNight = 2900m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AvailableRoomsCount = 2,
                            City = "Дніпро",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
                            Name = "Bartolomeo Resort",
                            PricePerNight = 4800m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AvailableRoomsCount = 5,
                            City = "Вінниця",
                            ImagePath = "https://images.unsplash.com/photo-1551882547-ff40c0d1398c",
                            Name = "Hotel France",
                            PricePerNight = 2500m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            AvailableRoomsCount = 3,
                            City = "Вінниця",
                            ImagePath = "https://images.unsplash.com/photo-1542314831-c6a4d27ce006",
                            Name = "Feride Hotel",
                            PricePerNight = 2800m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            AvailableRoomsCount = 2,
                            City = "Луцьк",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Name = "Noble Boutique Hotel",
                            PricePerNight = 2300m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            AvailableRoomsCount = 6,
                            City = "Луцьк",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
                            Name = "Zalesie Hotel",
                            PricePerNight = 1800m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            AvailableRoomsCount = 5,
                            City = "Донецьк",
                            ImagePath = "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
                            Name = "Donbass Palace",
                            PricePerNight = 4000m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            AvailableRoomsCount = 8,
                            City = "Донецьк",
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            Name = "Victoria Hotel",
                            PricePerNight = 3500m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            AvailableRoomsCount = 12,
                            City = "Житомир",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Reikartz Zhytomyr",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            AvailableRoomsCount = 4,
                            City = "Житомир",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "Chalet Hotel",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            AvailableRoomsCount = 5,
                            City = "Ужгород",
                            ImagePath = "https://images.unsplash.com/photo-1618773928121-c32242fa4703",
                            Name = "Hotel Duet Plus",
                            PricePerNight = 2600m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            AvailableRoomsCount = 7,
                            City = "Ужгород",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
                            Name = "Praha Hotel",
                            PricePerNight = 2200m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            AvailableRoomsCount = 8,
                            City = "Запоріжжя",
                            ImagePath = "https://images.unsplash.com/photo-1551882547-ff40c0d1398c",
                            Name = "Khortitsa Palace",
                            PricePerNight = 3100m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            AvailableRoomsCount = 15,
                            City = "Запоріжжя",
                            ImagePath = "https://images.unsplash.com/photo-1542314831-c6a4d27ce006",
                            Name = "Intourist Hotel",
                            PricePerNight = 1900m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            AvailableRoomsCount = 6,
                            City = "Івано-Франківськ",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Name = "Nadiya Hotel",
                            PricePerNight = 2400m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            AvailableRoomsCount = 4,
                            City = "Івано-Франківськ",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
                            Name = "Stanislaviv",
                            PricePerNight = 2000m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            AvailableRoomsCount = 9,
                            City = "Кропивницький",
                            ImagePath = "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
                            Name = "Reikartz Kropyvnytskyi",
                            PricePerNight = 2200m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            AvailableRoomsCount = 11,
                            City = "Кропивницький",
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            Name = "Hotel Zirka",
                            PricePerNight = 1600m,
                            Rating = 8.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            AvailableRoomsCount = 5,
                            City = "Луганськ",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Hotel Initial",
                            PricePerNight = 1800m,
                            Rating = 8.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            AvailableRoomsCount = 8,
                            City = "Луганськ",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "Druzhba Hotel",
                            PricePerNight = 1500m,
                            Rating = 8.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            AvailableRoomsCount = 7,
                            City = "Миколаїв",
                            ImagePath = "https://images.unsplash.com/photo-1618773928121-c32242fa4703",
                            Name = "Reikartz River",
                            PricePerNight = 2500m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            AvailableRoomsCount = 4,
                            City = "Миколаїв",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
                            Name = "Palace Ukraine",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            AvailableRoomsCount = 3,
                            City = "Полтава",
                            ImagePath = "https://images.unsplash.com/photo-1551882547-ff40c0d1398c",
                            Name = "Premier Hotel Palazzo",
                            PricePerNight = 2700m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            AvailableRoomsCount = 6,
                            City = "Полтава",
                            ImagePath = "https://images.unsplash.com/photo-1542314831-c6a4d27ce006",
                            Name = "Reikartz Gallery",
                            PricePerNight = 2300m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            AvailableRoomsCount = 2,
                            City = "Рівне",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Name = "Boutique Hotel",
                            PricePerNight = 2600m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            AvailableRoomsCount = 8,
                            City = "Рівне",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
                            Name = "Optima Rivne",
                            PricePerNight = 1900m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            AvailableRoomsCount = 5,
                            City = "Суми",
                            ImagePath = "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
                            Name = "Reikartz Sumy",
                            PricePerNight = 2000m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            AvailableRoomsCount = 3,
                            City = "Суми",
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            Name = "Shafran Hotel",
                            PricePerNight = 2200m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            AvailableRoomsCount = 6,
                            City = "Тернопіль",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Avalon Palace",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            AvailableRoomsCount = 4,
                            City = "Тернопіль",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "Garden Hall",
                            PricePerNight = 2100m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            AvailableRoomsCount = 10,
                            City = "Херсон",
                            ImagePath = "https://images.unsplash.com/photo-1618773928121-c32242fa4703",
                            Name = "Optima Kherson",
                            PricePerNight = 1800m,
                            Rating = 8.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            AvailableRoomsCount = 3,
                            City = "Херсон",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
                            Name = "Play Hotel by Ribas",
                            PricePerNight = 2300m,
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            AvailableRoomsCount = 4,
                            City = "Хмельницький",
                            ImagePath = "https://images.unsplash.com/photo-1551882547-ff40c0d1398c",
                            Name = "Arena Hotel",
                            PricePerNight = 2500m,
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            AvailableRoomsCount = 2,
                            City = "Хмельницький",
                            ImagePath = "https://images.unsplash.com/photo-1542314831-c6a4d27ce006",
                            Name = "Sobkoff Hotel",
                            PricePerNight = 2800m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            AvailableRoomsCount = 6,
                            City = "Черкаси",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945",
                            Name = "Apelsin Hotel",
                            PricePerNight = 2200m,
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            AvailableRoomsCount = 8,
                            City = "Черкаси",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
                            Name = "Optima Cherkasy",
                            PricePerNight = 1900m,
                            Rating = 8.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            AvailableRoomsCount = 5,
                            City = "Чернівці",
                            ImagePath = "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
                            Name = "Bukovyna Hotel",
                            PricePerNight = 2700m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            AvailableRoomsCount = 2,
                            City = "Чернівці",
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
                            Name = "AllureInn",
                            PricePerNight = 3000m,
                            Rating = 9.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            AvailableRoomsCount = 7,
                            City = "Чернігів",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Riverside Resort",
                            PricePerNight = 2400m,
                            Rating = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            AvailableRoomsCount = 5,
                            City = "Чернігів",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "Reikartz Chernihiv",
                            PricePerNight = 2100m,
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            AvailableRoomsCount = 4,
                            City = "Сімферополь",
                            ImagePath = "https://images.unsplash.com/photo-1618773928121-c32242fa4703",
                            Name = "Ukraina Hotel",
                            PricePerNight = 3500m,
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            AvailableRoomsCount = 2,
                            City = "Ялта",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
                            Name = "Yalta Intourist",
                            PricePerNight = 5500m,
                            Rating = 9.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            AvailableRoomsCount = 8,
                            City = "Буковель",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
                            Name = "Radisson Blu Resort",
                            PricePerNight = 6200m,
                            Rating = 9.3000000000000007
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            AvailableRoomsCount = 5,
                            City = "Буковель",
                            ImagePath = "https://images.unsplash.com/photo-1590490359683-658d3d23f972",
                            Name = "F&B Spa Resort",
                            PricePerNight = 5100m,
                            Rating = 9.0
                        });
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Booking.Models.Booking", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.FavoriteHotel", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.Review", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.HasOne("Booking.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Booking.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Booking.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Booking.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
